### ISSUE TITLE
Worst dualHooked grabber

### ISSUE THREAD

**Issue by Appolon24800** [ThunderboltDev/Thunder-Stealer#1]
BRO wee see the "Blacklistedip" its just a second graber don't use this shit

**Comment by ThunderboltDev** [comment]
LMAO ITS NOT A SECOND GRABBER DUMBASS😂😂 LMAOOO its blacklist ips and contacts my json file dumbass 💀

**Comment by ThunderboltDev** [comment]
thats why i have the blacklist url in it🤡
