### ISSUE TITLE
why is discord token grabbing regex and everything around it obfucsated?

### ISSUE THREAD

**Issue by KDot227** [ThunderboltDev/Thunder-Stealer#2]

**Comment by ThunderboltDev** [comment]
its makes it more FUD mostly sometimes but it also uses pyobfuscator to obfuscate the file i obfuscate some of the code so it can make it less detected while you use it but its safe i obfuscated some so it wont be detected by antivirus if you want to decode the obfuscated part i encoded it using base64 and marshal

**Comment by ThunderboltDev** [comment]
if you have any questions or answer i will happily help you!

**Comment by ThunderboltDev** [comment]
And i also used https://pyob.oxyry.com/

**Comment by ThunderboltDev** [comment]
but i will be here if you need me!

**Comment by KDot227** [comment]
> its makes it more FUD mostly sometimes but it also uses pyobfuscator to obfuscate the file i obfuscate some of the code so it can make it less detected while you use it but its safe i obfuscated some so it wont be detected by antivirus if you want to decode the obfuscated part i encoded it using base64 and marshal

Why not obfuscate that after and make a builder?

**Comment by KDot227** [comment]
It's not considered open src if it's partly obfuscated
